Staging workflow

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -14,11 +14,14 @@ on:
       - terraform/**
 
 env:
-  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  # Credentials for deployment to AWS
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}         # AWS Access Key ID
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS Secret Access Key
+
+  # S3 Bucket for the Terraform state
   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
-  AWS_REGION: us-east-1
-  EKS_CLUSTER: vprofile-eks
+  AWS_REGION: us-east-1                    # AWS region for resources
+  EKS_CLUSTER: vprofile-new-eks                 # EKS cluster name
 
 jobs:
   terraform:
@@ -31,40 +34,34 @@ jobs:
         working-directory: ./terraform
         
     steps:
+      # Checkout the repository
       - name: Checkout Source Code
         uses: actions/checkout@v4
 
+      # Set up Terraform
       - name: Set Up Terraform
         uses: hashicorp/setup-terraform@v2
         with:
-          terraform_version: 1.9.7
+          terraform_version: 1.9.7  # Specify your Terraform version
 
+      # Initialize Terraform
       - name: Terraform Init
         run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}"
 
+      # Check Terraform formatting
       - name: Terraform Format Check
         run: terraform fmt -check
 
+      # Validate Terraform configuration
       - name: Terraform Validate
         run: terraform validate
 
-      # Delete EKS Node Groups before destroying the cluster
-      - name: Delete EKS Node Groups
-        run: |
-          NODEGROUPS=$(aws eks list-nodegroups --cluster-name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} --query 'nodegroups' --output text)
-          if [ -n "$NODEGROUPS" ]; then
-            for NODEGROUP in $NODEGROUPS; do
-              aws eks delete-nodegroup --cluster-name ${{ env.EKS_CLUSTER }} --nodegroup-name $NODEGROUP --region ${{ env.AWS_REGION }}
-              echo "Deleting node group $NODEGROUP"
-              aws eks wait nodegroup-deleted --cluster-name ${{ env.EKS_CLUSTER }} --nodegroup-name $NODEGROUP --region ${{ env.AWS_REGION }}
-            done
-          fi
+      # Plan Terraform changes
+      - name: Terraform Plan
+        id: plan  # Add an ID to reference this step
+        run: terraform plan -no-color -input=false -out=planfile
 
-      # Sleep for 60 seconds to ensure AWS propagates the node group deletion
-      - name: Wait for Node Group Deletion to Propagate
-        run: sleep 60
-
-      # Destroy all resources
-      - name: Terraform Destroy
-        run: terraform destroy -no-color -input=false -auto-approve
-####
+      # Check if the Terraform Plan step failed
+      - name: Terraform Plan Status
+        if: ${{ steps.plan.outcome == 'failure' }}
+        run: exit 1
